server:
  port: 8080
spring:
  application:
    name: sa-token
  config:
    import:
      - application-web.yml
      - application-log.yml
      - application-saToken.yml
      - application-redis.yml